name: Main
on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: ls -lah
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync ./build s3://${{ secrets.FRONTEND_NAME }}
      - name: Invalidate CloudFront Cache
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
      - run:
          cd terraform && terraform init && terraform state pull > state.tfstate && cat state.tfstate
          # - aws cloudfront create-invalidation --distribution-id E1JF94CYWJSGD8 --paths "/*"
